# Generated by Django 5.2.14 on 2026-05-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Hi, I'm", max_length=100)),
                ("name", models.CharField(default="Izengo Maganga", max_length=200)),
                (
                    "subtitle",
                    models.CharField(default="Data Scientist", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="I'm a passionate front-end developer with one year of professional experience..."
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="page/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Profile",
                "verbose_name_plural": "Portfolio Profile",
            },
        ),
    ]
