# Generated by Django 5.2.14 on 2026-05-23 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="title",
        ),
    ]
