# Generated by Django 5.2.14 on 2026-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Data Science with 1 Year of Experience", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="I’m a dedicated front-end developer with one year of experience creating professional, responsive web applications. My work focuses on delivering polished user interfaces and seamless user experiences using modern web technologies."
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        default="React.js, Next.js, Bootstrap, JavaScript, CSS3, HTML5",
                        max_length=500,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Content",
                "verbose_name_plural": "About Content",
            },
        ),
    ]
